package org.rio.bean;

import lombok.Data;
import lombok.AllArgsConstructor;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.NoArgsConstructor;
import lombok.Builder;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName("users")
public class Users {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CURRENT_CONNECTIONS
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.TOTAL_CONNECTIONS
     *
     * @mbg.generated
     */
    private String password;

}