package org.rio.mapper;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Param;
import org.rio.bean.Menus;
import org.rio.bean.MenusExample;

public interface MenusMapper extends BaseMapper<Menus> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    long countByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int deleteByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int insert(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int insertSelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    List<Menus> selectByExample(MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    Menus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Menus record, @Param("example") MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Menus record, @Param("example") MenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Menus record);
}